### ISSUE TITLE
TODO memo

### ISSUE THREAD

**Issue by jsupratman13** [jsupratman13/hajime_walk_ros#1]
**Overview**

List of things needed to do:
- [ ] refactor hajime walk control
   - [ ] remove unused code, avoid forward declaration if possible
   - [ ] fix license
- [ ] improve hajime walk control
   - [ ] use urdf or tf to extract mechanical data
   - [ ] calculate odom
   - [ ] calculate base footprint
- [ ] finish in rqt_hajime_motion_creator
   - [ ] fix bug (frame deletion/label)
   - [ ] left/right frame switch
   - [ ] option to change pub/sub topic
- [ ] hajime_teleop continuous mode
   - [ ] add flag to enable continuous walking
